// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Telzir.Models;

namespace Telzir.Migrations
{
    [DbContext(typeof(TelzirContext))]
    partial class TelzirContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Telzir.Models.Pacote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<int>("Minutos");

                    b.Property<int?>("PlanoId");

                    b.Property<int>("Tipo");

                    b.HasKey("Id");

                    b.HasIndex("PlanoId");

                    b.ToTable("Pacote");
                });

            modelBuilder.Entity("Telzir.Models.Plano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Criado");

                    b.Property<string>("Descricao");

                    b.Property<DateTime>("Editado");

                    b.Property<string>("Nome");

                    b.Property<decimal>("Porcentagem");

                    b.Property<int?>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Plano");
                });

            modelBuilder.Entity("Telzir.Models.Tarifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DdDestino");

                    b.Property<int>("DdOrigem");

                    b.Property<decimal>("Valor");

                    b.HasKey("Id");

                    b.ToTable("Tarifa");
                });

            modelBuilder.Entity("Telzir.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Login");

                    b.Property<string>("Nome");

                    b.Property<string>("Senha");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Telzir.Models.Pacote", b =>
                {
                    b.HasOne("Telzir.Models.Plano", "Plano")
                        .WithMany()
                        .HasForeignKey("PlanoId");
                });

            modelBuilder.Entity("Telzir.Models.Plano", b =>
                {
                    b.HasOne("Telzir.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
